### PR TITLE
Ms3 verification test

### PR DESCRIPTION
**Pull request by VdotR**
Added tests for email and verification

### CODE REVIEW

**Review by cbaeucsd — CHANGES_REQUESTED** [review]
no tests actually check the resend_verification route nor the signup email sending

**Comment by VdotR** [comment]
OK will work on that in a bit

**Comment by VdotR** [comment]
Added the tests you were mentioning

**Review by cbaeucsd — APPROVED** [review]
Looks good.

Now that I think about it resend_verification should check if user isn't validated first. We can work on that another time.

**Comment by VdotR** [comment]
> Looks good.
> 
> Now that I think about it resend_verification should check if user isn't validated first. We can work on that another time.

OK, added this to the security concerns doc.

**Pull request merged**
