### PR TITLE
Ms3 CI test for poll routes

### PR DESCRIPTION
**Pull request by trdavidt**
Added tests for poll routes

### CODE REVIEW

**Comment by cbaeucsd** [comment]
holding off until
- poll and user.js are tested
- user.routes.test is standardized to look more liike poll.routes.js
- maybe use https://www.npmjs.com/package/mockingoose as well

**Comment by cbaeucsd** [comment]
@trdavidt can you also add more comments on some of the invalid cases clarify what exactly about their invalidity you are trying to test

**Review by cbaeucsd — CHANGES_REQUESTED** [review]
Decided not to use mockingoose for now
Waiting for comments on tests from David

**Comment by trdavidt** [comment]
Looks good, I'll finish up my part after my midterm tomorrow morning

**Review by trdavidt — COMMENTED** [review]
Added comments as requested

**Review by cbaeucsd — APPROVED** [review]

**Pull request merged**
