### PR TITLE
Ms2 quickpoll

### PR DESCRIPTION
**Pull request by VdotR**
#10

### CODE REVIEW

**Comment by cbaeucsd** [comment]
is making a new route the best choice for this?

otherwise 1 random console.log remaining in code

**Comment by VdotR** [comment]
I'll try doing it with our current route

**Comment by VdotR** [comment]
@cbaeucsd Implemented using existing poll route, can you please check again?

**Review by cbaeucsd — APPROVED** [review]
everything looks good to me

**Pull request merged**
