### PR TITLE
show shortid in dialog with qr code on poll details

### PR DESCRIPTION
**Pull request by trdavidt**
Short ID is printed in dialog on poll details page

### CODE REVIEW

**Comment by trdavidt** [comment]
Closes #14

**Comment by cbaeucsd** [comment]
Present still shows QR code, no shortId if poll is not available. Check/reminder/option should be placed for user to set available when clicking present?

**Comment by trdavidt** [comment]
I added the availability toggle on the poll details and hid the "present" dialog when the poll isn't available

**Review by cbaeucsd — APPROVED** [review]
Only skimmed through the polldetails.jsx changes, but that and testing of the page seems fine to me. Good work on the misc stuff too

**Pull request merged**
